### ISSUE TITLE
backup manager will not backup the DB if it is stored on a other location

### ISSUE THREAD

**Issue by AlexanderTurnowsky** [maforget/cr-backup-manager#1]
First of all great work,
i use in the Comicrack.ini the DatabasePath = G:\ComicRack\db\.
When i'm now using the backup manager this DB will not be in the backup, only the files from the Roaming folder.
Would there be a possibility to read out this setting from the ini and forward it to the backup manager?

thx
Alex

**Comment by maforget** [comment]
I can't really read the ComicRack.ini, because it can be in a multitude of places (%APPDATA%, %PROGRAMDATA%, Install directory, Data folder for portable mode or in a sub configuration folder for any of these). Some of these places we have no idea where they are. Also some of these values can be passed via command lines, like the database path itself.

We would need to read the path directly from ComicRack. I don't believe it is available to plugins.

What we have now is already miles ahead of what it did before, since the path was just hardcoded and didn't support all these options. The scripts determines the Db location by checking where the script is ran, that way it can supports all these config. But that db must be next to the Script folder.

But since you already specified an alternative path for the DB, you could easily back it up. Like set that path to a cloud monitored folder like Dropbox, OneDrive, GDrive or MEGA.

**Comment by AlexanderTurnowsky** [comment]
ok no problem here is what i have done.
generated the following in the bmUtils.py:
```
myDBDataFolder = 'g:\\ComicRack\\db' + '\\'
myDBFile = Path.Combine(myDBDataFolder,'ComicDB.xml')
```

and added to both backupmethods:
`zipfile.AddFile(myDBFile, '')`

With this changes it is working.
Thx
Alex
